version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: snowpack
    versions:
    - 3.0.11
    - 3.0.13
    - 3.1.2
    - 3.2.2
    - 3.3.0
    - 3.3.3
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: workbox-cli
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.33.0
    - 3.34.0
    - 3.35.0
  - dependency-name: prettier-plugin-svelte
    versions:
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.1.5
    - 2.1.6
  - dependency-name: "@snowpack/app-scripts-svelte"
    versions:
    - 2.0.0
